---
version: "2.1"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      # - WHITELIST=iplist #optional
      - HOST_WHITELIST=dnsnane list #optional
    volumes:
      - ./transmission:/config
      - ./transmission:/downloads
      - ./transmission:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - atlas_net

  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    hostname: mongoclient
    depends_on:
      - mongodb
    ports:
      - 3300:3000
    environment:
      - MONGO_URL=${MONGO_URI}
    networks:
      - atlas_net

volumes:
  transmission:
  mongodb:

networks:
  atlas_net:
    driver: bridge
